baseurl = "/"
languageCode = "de-de"
title = "Books and Just All I Love"
paginate = 10

theme = "hugo-strata-theme"

[params]
  name = "Fenja Hildebrandt"
  description = "Mein Blog über Bücher und was ich sonst noch so liebe"

  date_format = "Mon, Jan 2, 2006"

  [params.contact]
  hide = true

  [params.sidebar]
    bio = "Mein Blog über Bücher und was ich sonst noch so liebe"

    twitter = "loesidoesi"

  [params.about]
    hide = false
    title = "Books and all I love"
    content = "Edison bulb palo santo godard disrupt fanny pack cloud bread lumbersexual distillery cred semiotics flannel. Polaroid microdosing dreamcatcher kitsch. Fashion axe microdosing wolf occupy, XOXO brooklyn chicharrones narwhal pickled squid. Polaroid hell of leggings salvia franzen actually shaman."

  [params.allposts]
    hide = false
    title = "Alle Blogeinträge"

  [params.portfolio]
    hide = false

[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 5


[[menu.main]]
  name = "Impressum"
  url = "impressum/"
  weight = 0
